### ISSUE TITLE
能否增加上下按键滑动的功能？

### ISSUE THREAD

**Issue by dengxueru** [wangeditor-team/wangEditor-plugin-mention#3]
1、支持隐藏搜索框参数
2、支持上下按键功能
3、@唤起默认选中第一个人

**Comment by wangfupeng1988** [comment]
这些都是你自己要做的

wangEditor 只接收一个 `showModal` 函数和一个 `hideModal` 函数，其他的你自己实现。
参考文档 https://github.com/wangeditor-team/wangEditor-plugin-mention
