### ISSUE TITLE
能否提供 react的例子

### ISSUE THREAD

**Issue by yuluo-zy** [wangeditor-team/wangEditor-plugin-mention#4]

**Comment by wangfupeng1988** [comment]
第一，你先用 React demo 把编辑器运行起来 https://www.wangeditor.com/v5/for-frame.html#react

第二，然后参考这个文档自行扩展即可 https://github.com/wangeditor-team/wangEditor-plugin-mention

第三，也可以对比参考 Vue 的示例 https://juejin.cn/post/7069548140294045709
