### ISSUE TITLE
在提及上扩展

### ISSUE THREAD

**Issue by Homebrew1** [wangeditor-team/wangEditor-plugin-mention#5]
移入提及元素<span data-w-e-type=\"mention\" data-w-e-is-void data-w-e-is-inline data-value=\"Rita Chan\" data-info=\"%7B%22value%22%3A%22Rita%20Chan%22%7D\"></span>，移入显示元素的tooltip 查询更多信息

**Comment by wangfupeng1988** [comment]
没懂你的意思

**Comment by lancyJD** [comment]
如何监听 mention元素被删除了？

**Comment by wangfupeng1988** [comment]
@lancyJD 监听删除，你想通过这个来做什么？

**Comment by lumosxin** [comment]
他意思可能是鼠标放上去，有个tooltip显示更多
![image](https://user-images.githubusercontent.com/99231682/186833471-556b9b14-7bf5-4ad8-9e30-541a70eaf8d3.png)

**Comment by pigcaso** [comment]
@wangfupeng1988 可以不通过mention-input的输入值来过滤list吗，输入‘@’之后继续在Editor中输入需要@人的数据然后根据新输入的数据来过滤list的值（就像现在使用的这个回复框的@功能一样）
 或者说有没有办法取消默认使modal关闭的事件呢，当我继续向Editor中输入数据时modal就自动关闭了（希望大佬能帮忙指点一下，蟹蟹）
<img width="382" alt="1662353896(1)" src="https://user-images.githubusercontent.com/49849107/188363605-11cc58ca-a89f-4135-9e0c-ef6c00794776.png">

**Comment by pigcaso** [comment]
以及对于最后生成的span标签能不能够给它添加自定义事件和样式鸭

**Comment by wangfupeng1988** [comment]
@pigcaso  showModal 和 hideModal 都是自己定义的，想怎么实现自己做即可

```js
// 编辑器配置
const editorConfig: Partial<IEditorConfig> = {
  EXTEND_CONF: {
    mentionConfig: {
      showModal, // 必须
      hideModal, // 必须
    },
  },

  // 其他...
}
```
